nome= input('Olá, insira seu nome')
print('Seja bem vindo ao seu primeiro projeto'+nome+'!' )
print('Vejo que possue o conhecimento inicial para uma mensagem interativa, vamos para o proximo exercicio')
input('Consegue criar uma mensagem interativa perguntando qual é sua idade?')
print('Vamos testar!')
dia=input('Em que dia voê nasceu?')
mês=input('De qual mês?')
ano=input('E qual ano?')
print('Então você nasceu dia',dia,'de',mês,'de',ano)
soma=int(2026)-int(ano)
print('Logo, suponho que você tem ou fara',soma,'anos!')